TIB Terminology Service search integration
ArunaStorage/website pull request #96
Opened 2024-08-01 06:42 UTC by das-Abroxas

This pull request introduces the direct integration of the TIB Terminology Service search into the resource creation form. With this integration, users can now search for and select ontologies from the TIB Terminology Service directly through our platform. Once an ontology is selected, it is added as valid JSON-LD to the resource, ensuring conformity with semantic web standards for content description.

## Changes
- Remove duplicate Preline dependencies
- Update remaining packages to latest versions
- Basic TIB Terminology Service API integration
- Small layout changes

2024-08-01 07:08 UTC, St4NNi requested changes
Just a few minor points, especially regarding the naming scheme.

2024-08-01 07:08 UTC, St4NNi commented on composables/ts_api/OntologyDoc.ts
Maybe I'm a little bit nit-picky but it is weird that we have multiple naming schemes for `.ts` files.
CamelCase, snake_case etc. we should choose one and stay with it.

2024-08-01 07:08 UTC, St4NNi commented on server/api/ontology.get.ts
I really don't like this solution. But for a first iteration this is fine, ideally we should ask the TIB people to expand their API to make it work without a wrapper. and/or to create our own handler that pre-processes the JSON on the client side.

2024-08-01 14:12 UTC, das-Abroxas commented on composables/ts_api/OntologyDoc.ts
This is not so easy with WebApp projects, as there are normally different nomenclatures according to the content of the files. 

Let's assume that we are guided by the [examples of the framework](https://github.com/nuxt/examples) that we use:
- **Components:** PascalCase
- **Composables:** If content type/class definition PascalCase; CamelCase otherwise
- **Middleware:** kebab-case
- **API routes:** kebab-case
- **Pages:** kebab-case
- And so on ...

I have now adapted the files changed in this pull request to this naming scheme. The rest will be revised in a future pull request, as this would otherwise go beyond the scope of this article. Thanks for pointing this out, it will make things easier for everyone in future.

2024-08-01 14:25 UTC, das-Abroxas commented on server/api/ontology.get.ts
This server-side implementation has nothing to do with the Terminology Service API, but with the fact that I wanted to have all API fetch routes in one place in this project.

From a performance point of view, this is not the smartest decision, but it gives me the advantage of only having to look in one place. As the number of endpoints has increased significantly in the meantime, we should definitely come up with a better concept for which API fetches should be sent on the server side and which on the client side. 

This will require a significant amount of refactoring and is therefore beyond the scope of this PR, but will be put on the agenda for future development with appropriate priority.

2024-08-02 07:11 UTC, St4NNi approved these changes
Thanks for the changes, this looks good now !

2024-08-02 07:12 UTC, merged